#!/bin/sh

dname=/data/.fio-test-$$
mkdir -p $dname
cd $dname

#fio --name=randwrite --ioengine=libaio --iodepth=1 --rw=randwrite --bs=4k --direct=0 --size=512M --numjobs=8 --runtime=240 --group_reporting
RV=$?
fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test --numjobs=8 --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75 --runtime=240
cd /tmp
rm -rf $dname
exit $RV
